spring:
  application:
    name: university portal
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true